/* AUTH */

export const USER_LOGGED_IN = 'LOGGED_IN';
export const USER_SIGNUP = 'SIGNUP';
export const USER_REFRESH_TOKEN = 'REFRESH_TOKEN';
export const USER_WHOAMI = 'WHOAMI';
export const AUTH_UPDATE_PASSWORD = 'AUTH_UPDATE_PASSWORD';

/* DASHBOARD */

export const GET_DASHBOARD = 'GET_DASHBOARD';

/* ORGANIZATION */

export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const FIND_ORGANIZATION_PAGE = 'FIND_ORGANIZATION_PAGE';
export const REMOVE_ORGANIZATION = 'REMOVE_ORGANIZATION';
export const FIND_ORGANIZATION = 'FIND_ORGANIZATION';

/* ORGANIZATION */

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const FIND_PROJECT_PAGE = 'FIND_PROJECT_PAGE';
export const FIND_PROJECT_BY_APPROVAL_STATUS = 'FIND_PROJECT_BY_APPROVAL_STATUS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const SOFT_DELETE_PROJECT = 'SOFT_DELETE_PROJECT';
export const FIND_PROJECT = 'FIND_PROJECT';

/* _APPROVAL_FLOW */

export const CREATE_APPROVAL_FLOW = 'CREATE_APPROVAL_FLOW';
export const UPDATE_APPROVAL_FLOW = 'UPDATE_APPROVAL_FLOW';
export const FIND_APPROVAL_FLOW_PAGE = 'FIND_APPROVAL_FLOW_PAGE';
export const REMOVE_APPROVAL_FLOW = 'REMOVE_APPROVAL_FLOW';
export const FIND_APPROVAL_FLOW = 'FIND_APPROVAL_FLOW';
export const FIND_APPROVAL_FLOW_BY_NAME = 'FIND_APPROVAL_FLOW_BY_NAME';

/* PROJECT_PLANNING */

export const CREATE_PROJECT_PLANNING = 'CREATE_PROJECT_PLANNING';
export const UPDATE_PROJECT_PLANNING = 'UPDATE_PROJECT_PLANNING';
export const FIND_PROJECT_PLANNING_PAGE = 'FIND_PROJECT_PLANNING_PAGE';
export const FIND_PROJECT_PLANNING_ALL = 'FIND_PROJECT_PLANNING_ALL';
export const REMOVE_PROJECT_PLANNING = 'REMOVE_PROJECT_PLANNING';
export const FIND_PROJECT_PLANNING = 'FIND_PROJECT_PLANNING';

/* PROJECT_SUMMARY */

export const CREATE_PROJECT_SUMMARY = 'CREATE_PROJECT_SUMMARY';
export const UPDATE_PROJECT_SUMMARY = 'UPDATE_PROJECT_SUMMARY';
export const FIND_PROJECT_SUMMARY_ALL = 'FIND_PROJECT_SUMMARY_ALL';
export const REMOVE_PROJECT_SUMMARY = 'REMOVE_PROJECT_SUMMARY';
export const FIND_PROJECT_SUMMARY = 'FIND_PROJECT_SUMMARY';

/* PROJECT_TIMELINE */

export const CREATE_PROJECT_TIMELINE = 'CREATE_PROJECT_TIMELINE';
export const UPDATE_PROJECT_TIMELINE = 'UPDATE_PROJECT_TIMELINE';
export const FIND_PROJECT_TIMELINE_ALL = 'FIND_PROJECT_TIMELINE_ALL';
export const REMOVE_PROJECT_TIMELINE = 'REMOVE_PROJECT_TIMELINE';
export const FIND_PROJECT_TIMELINE = 'FIND_PROJECT_TIMELINE';

/* COMMENTS */

export const CREATE_COMMENTS = 'CREATE_COMMENTS';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const FIND_COMMENTS_PAGE = 'FIND_COMMENTS_PAGE';
export const REMOVE_COMMENTS = 'REMOVE_COMMENTS';
export const FIND_COMMENTS = 'FIND_COMMENTS';

/* NOTIFICATIONS */

export const CREATE_NOTIFICATIONS = 'CREATE_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const FIND_NOTIFICATIONS_PAGE = 'FIND_NOTIFICATIONS_PAGE';
export const REMOVE_NOTIFICATIONS = 'REMOVE_NOTIFICATIONS';
export const FIND_NOTIFICATIONS = 'FIND_NOTIFICATIONS';

/* PREDECESSOR */

export const CREATE_PREDECESSOR = 'CREATE_PREDECESSOR';
export const UPDATE_PREDECESSOR = 'UPDATE_PREDECESSOR';
export const FIND_PREDECESSOR_PAGE = 'FIND_PREDECESSOR_PAGE';
export const REMOVE_PREDECESSOR = 'REMOVE_PREDECESSOR';
export const FIND_PREDECESSOR = 'FIND_PREDECESSOR';

/* PREDECESSOR */

export const CREATE_WEIGHT_DETAIL = 'CREATE_WEIGHT_DETAIL';
export const UPDATE_WEIGHT_DETAIL = 'UPDATE_WEIGHT_DETAIL';
export const FIND_WEIGHT_DETAIL_PAGE = 'FIND_WEIGHT_DETAIL_PAGE';
export const REMOVE_WEIGHT_DETAIL = 'REMOVE_WEIGHT_DETAIL';
export const FIND_WEIGHT_DETAIL = 'FIND_WEIGHT_DETAIL';

/* USERS */

export const CREATE_USER = 'CREATE_USER';
export const FIND_USER_PAGE = 'FIND_USER_PAGE';
export const FIND_USER_PAGE_ROLE = 'FIND_USER_PAGE_ROLE';
export const FIND_USER_PERMISSION = 'FIND_USER_PERMISSION';
export const FIND_USER_DETAIL = 'FIND_USER_DETAIL';
export const UPDATE_USER_ROLE = 'UPDATE_USER_ROLE';
export const REMOVE_USER = 'REMOVE_USER';
export const FIND_USER_BY_ID = 'FIND_USER_BY_ID';
export const FIND_USER_EMAIL = 'FIND_USER_EMAIL';
export const FIND_USER_ROLE_PERMISSION = 'FIND_USER_ROLE_PERMISSION';

/* USER - ROLE  */
export const CREATE_USER_ROLE = 'CREATE_USER_ROLE';
export const FIND_USER_ROLE_BY_CODE = 'FIND_USER_ROLE_BY_CODE';
export const FIND_USER_ROLE_DETAIL = 'FIND_USER_ROLE_DETAIL';
export const FIND_USER_ROLE_PAGE = 'FIND_USER_ROLE_PAGE';
export const REMOVE_USER_ROLE = 'REMOVE_USER_ROLE';


/* DASHBOARDSCOPE */

export const GET_DASHBOARDSCOPE = 'GET_DASHBOARDSCOPE';
export const CREATE_DASHBOARDSCOPE = 'CREATE_DASHBOARDSCOPE';
export const UPDATE_DASHBOARDSCOPE = 'UPDATE_DASHBOARDSCOPE';
export const FIND_DASHBOARDSCOPE_PAGE = 'FIND_DASHBOARDSCOPE_PAGE';
export const REMOVE_DASHBOARDSCOPE = 'REMOVE_DASHBOARDSCOPE';
export const FIND_DASHBOARDSCOPE = 'FIND_DASHBOARDSCOPE';